<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeAlpha_EventRegistrationSystem.Core\CodeAlpha_EventRegistrationSystem.Core.csproj" />
  </ItemGroup>

</Project>
